/**
 * ══════════════════════════════════════════════════════════════════════════════
 * OCCASION TRAINING DATA — 500+ Labelled Samples for Decision Tree & KNN
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * Each sample represents a hypothetical outfit with extracted features:
 *   - formality     : average formality score (1-5)
 *   - neutralRatio  : fraction of neutral colors (0-1)
 *   - saturationAvg : average HSL saturation (0-100)
 *   - lightnessAvg  : average HSL lightness (0-100)
 *   - warmthScore   : fraction of warm-toned colors (0-1)
 *   - hueVariance   : variance in hue values (0-32400)
 *   - formalityRange : max-min formality (0-4)
 *   - label         : target occasion class
 *
 * Classes: Office, Casual, College, Party, Date Night, Formal, Wedding,
 *          Sports, Festival, Brunch, Travel, Beach, Interview, Cocktail,
 *          Business Casual, Streetwear, Ethnic Festive, Night Out
 *
 * Manually curated with controlled feature distributions to ensure
 * balanced class representation and clear decision boundaries.
 */

export interface ExtendedTrainingSample {
  formality: number;
  neutralRatio: number;
  saturationAvg: number;
  lightnessAvg: number;
  warmthScore: number;
  hueVariance: number;
  formalityRange: number;
  dominantTraits: string[];
  label: string;
}

export const EXTENDED_OCCASION_TRAINING_DATA: ExtendedTrainingSample[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // OFFICE / WORK (40 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 4.0, neutralRatio: 0.60, saturationAvg: 25, lightnessAvg: 45, warmthScore: 0.3, hueVariance: 200, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 3.5, neutralRatio: 0.50, saturationAvg: 30, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 300, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Office" },
  { formality: 4.5, neutralRatio: 0.70, saturationAvg: 20, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 100, formalityRange: 1, dominantTraits: ["formal","elegant"], label: "Office" },
  { formality: 3.0, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 50, warmthScore: 0.5, hueVariance: 400, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 4.0, neutralRatio: 0.55, saturationAvg: 28, lightnessAvg: 42, warmthScore: 0.3, hueVariance: 250, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Office" },
  { formality: 3.5, neutralRatio: 0.65, saturationAvg: 22, lightnessAvg: 38, warmthScore: 0.2, hueVariance: 150, formalityRange: 1, dominantTraits: ["classic","formal"], label: "Office" },
  { formality: 4.0, neutralRatio: 0.50, saturationAvg: 32, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 350, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Office" },
  { formality: 3.8, neutralRatio: 0.58, saturationAvg: 27, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 220, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 4.2, neutralRatio: 0.62, saturationAvg: 24, lightnessAvg: 41, warmthScore: 0.2, hueVariance: 180, formalityRange: 1, dominantTraits: ["formal","elegant"], label: "Office" },
  { formality: 3.5, neutralRatio: 0.48, saturationAvg: 33, lightnessAvg: 52, warmthScore: 0.5, hueVariance: 420, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 3.7, neutralRatio: 0.52, saturationAvg: 29, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 280, formalityRange: 1, dominantTraits: ["classic","minimalist"], label: "Office" },
  { formality: 4.3, neutralRatio: 0.68, saturationAvg: 21, lightnessAvg: 39, warmthScore: 0.2, hueVariance: 120, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Office" },
  { formality: 3.3, neutralRatio: 0.45, saturationAvg: 34, lightnessAvg: 51, warmthScore: 0.4, hueVariance: 380, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 4.1, neutralRatio: 0.58, saturationAvg: 26, lightnessAvg: 43, warmthScore: 0.3, hueVariance: 210, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 3.6, neutralRatio: 0.53, saturationAvg: 31, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 320, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Office" },
  { formality: 4.0, neutralRatio: 0.60, saturationAvg: 25, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 190, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 3.9, neutralRatio: 0.55, saturationAvg: 28, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 240, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Office" },
  { formality: 4.4, neutralRatio: 0.72, saturationAvg: 18, lightnessAvg: 37, warmthScore: 0.1, hueVariance: 80, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Office" },
  { formality: 3.4, neutralRatio: 0.47, saturationAvg: 33, lightnessAvg: 50, warmthScore: 0.5, hueVariance: 390, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 3.8, neutralRatio: 0.56, saturationAvg: 27, lightnessAvg: 45, warmthScore: 0.3, hueVariance: 230, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 4.0, neutralRatio: 0.63, saturationAvg: 23, lightnessAvg: 41, warmthScore: 0.2, hueVariance: 160, formalityRange: 1, dominantTraits: ["formal","elegant"], label: "Office" },
  { formality: 3.6, neutralRatio: 0.50, saturationAvg: 30, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 310, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Office" },
  { formality: 4.2, neutralRatio: 0.64, saturationAvg: 22, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 140, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 3.5, neutralRatio: 0.48, saturationAvg: 32, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 360, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 3.9, neutralRatio: 0.57, saturationAvg: 26, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 220, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 4.1, neutralRatio: 0.61, saturationAvg: 24, lightnessAvg: 42, warmthScore: 0.2, hueVariance: 170, formalityRange: 1, dominantTraits: ["formal","elegant"], label: "Office" },
  { formality: 3.7, neutralRatio: 0.52, saturationAvg: 30, lightnessAvg: 47, warmthScore: 0.4, hueVariance: 290, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Office" },
  { formality: 4.3, neutralRatio: 0.66, saturationAvg: 21, lightnessAvg: 39, warmthScore: 0.2, hueVariance: 130, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Office" },
  { formality: 3.4, neutralRatio: 0.44, saturationAvg: 34, lightnessAvg: 52, warmthScore: 0.5, hueVariance: 410, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 3.8, neutralRatio: 0.54, saturationAvg: 29, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 260, formalityRange: 1, dominantTraits: ["classic","formal"], label: "Office" },
  { formality: 4.0, neutralRatio: 0.59, saturationAvg: 25, lightnessAvg: 43, warmthScore: 0.3, hueVariance: 200, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 3.6, neutralRatio: 0.50, saturationAvg: 31, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 330, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Office" },
  { formality: 4.2, neutralRatio: 0.65, saturationAvg: 22, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 145, formalityRange: 1, dominantTraits: ["formal","elegant"], label: "Office" },
  { formality: 3.5, neutralRatio: 0.47, saturationAvg: 33, lightnessAvg: 51, warmthScore: 0.5, hueVariance: 400, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 3.9, neutralRatio: 0.56, saturationAvg: 27, lightnessAvg: 45, warmthScore: 0.3, hueVariance: 235, formalityRange: 1, dominantTraits: ["formal","classic"], label: "Office" },
  { formality: 4.1, neutralRatio: 0.60, saturationAvg: 24, lightnessAvg: 42, warmthScore: 0.2, hueVariance: 175, formalityRange: 1, dominantTraits: ["formal","elegant"], label: "Office" },
  { formality: 3.7, neutralRatio: 0.51, saturationAvg: 30, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 300, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Office" },
  { formality: 4.4, neutralRatio: 0.70, saturationAvg: 19, lightnessAvg: 38, warmthScore: 0.1, hueVariance: 90, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Office" },
  { formality: 3.3, neutralRatio: 0.43, saturationAvg: 35, lightnessAvg: 53, warmthScore: 0.5, hueVariance: 430, formalityRange: 1, dominantTraits: ["classic","preppy"], label: "Office" },
  { formality: 3.8, neutralRatio: 0.55, saturationAvg: 28, lightnessAvg: 45, warmthScore: 0.3, hueVariance: 245, formalityRange: 1, dominantTraits: ["classic","formal"], label: "Office" },

  // ══════════════════════════════════════════════════════════════════════════
  // CASUAL (40 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 1.0, neutralRatio: 0.30, saturationAvg: 40, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 600, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 500, formalityRange: 0, dominantTraits: ["casual","minimalist"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 55, warmthScore: 0.6, hueVariance: 800, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 55, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 900, formalityRange: 0, dominantTraits: ["casual","edgy"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.35, saturationAvg: 38, lightnessAvg: 52, warmthScore: 0.5, hueVariance: 550, formalityRange: 0, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.25, saturationAvg: 42, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 700, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.45, saturationAvg: 32, lightnessAvg: 48, warmthScore: 0.3, hueVariance: 400, formalityRange: 1, dominantTraits: ["casual","minimalist"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.30, saturationAvg: 45, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 650, formalityRange: 0, dominantTraits: ["casual","trendy"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 48, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 750, formalityRange: 0, dominantTraits: ["casual","edgy"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.35, saturationAvg: 40, lightnessAvg: 52, warmthScore: 0.5, hueVariance: 580, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 1.2, neutralRatio: 0.28, saturationAvg: 43, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 680, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 1.8, neutralRatio: 0.38, saturationAvg: 36, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 480, formalityRange: 0, dominantTraits: ["casual","minimalist"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.22, saturationAvg: 52, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 850, formalityRange: 0, dominantTraits: ["casual","edgy"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.32, saturationAvg: 42, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 620, formalityRange: 0, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.40, saturationAvg: 38, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 520, formalityRange: 1, dominantTraits: ["casual","preppy"], label: "Casual" },
  { formality: 1.3, neutralRatio: 0.27, saturationAvg: 44, lightnessAvg: 57, warmthScore: 0.6, hueVariance: 700, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 1.7, neutralRatio: 0.36, saturationAvg: 37, lightnessAvg: 51, warmthScore: 0.4, hueVariance: 490, formalityRange: 0, dominantTraits: ["casual","minimalist"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.18, saturationAvg: 50, lightnessAvg: 62, warmthScore: 0.7, hueVariance: 880, formalityRange: 0, dominantTraits: ["casual","bold"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.33, saturationAvg: 41, lightnessAvg: 53, warmthScore: 0.5, hueVariance: 600, formalityRange: 0, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.42, saturationAvg: 34, lightnessAvg: 48, warmthScore: 0.3, hueVariance: 420, formalityRange: 1, dominantTraits: ["casual","minimalist"], label: "Casual" },
  { formality: 1.2, neutralRatio: 0.25, saturationAvg: 46, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 720, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 1.8, neutralRatio: 0.37, saturationAvg: 36, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 500, formalityRange: 0, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 48, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 800, formalityRange: 0, dominantTraits: ["casual","edgy"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.30, saturationAvg: 43, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 650, formalityRange: 0, dominantTraits: ["casual","trendy"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.38, saturationAvg: 39, lightnessAvg: 51, warmthScore: 0.5, hueVariance: 540, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 1.3, neutralRatio: 0.26, saturationAvg: 44, lightnessAvg: 57, warmthScore: 0.6, hueVariance: 710, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 1.7, neutralRatio: 0.35, saturationAvg: 37, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 510, formalityRange: 0, dominantTraits: ["casual","minimalist"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.19, saturationAvg: 51, lightnessAvg: 61, warmthScore: 0.7, hueVariance: 860, formalityRange: 0, dominantTraits: ["casual","bold"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.31, saturationAvg: 42, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 630, formalityRange: 0, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 460, formalityRange: 1, dominantTraits: ["casual","preppy"], label: "Casual" },
  { formality: 1.2, neutralRatio: 0.24, saturationAvg: 45, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 740, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 1.8, neutralRatio: 0.36, saturationAvg: 38, lightnessAvg: 51, warmthScore: 0.4, hueVariance: 500, formalityRange: 0, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.21, saturationAvg: 49, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 820, formalityRange: 0, dominantTraits: ["casual","edgy"], label: "Casual" },
  { formality: 1.5, neutralRatio: 0.33, saturationAvg: 40, lightnessAvg: 53, warmthScore: 0.5, hueVariance: 610, formalityRange: 0, dominantTraits: ["casual","trendy"], label: "Casual" },
  { formality: 1.9, neutralRatio: 0.39, saturationAvg: 37, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 520, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 1.1, neutralRatio: 0.23, saturationAvg: 47, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 760, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Casual" },
  { formality: 1.6, neutralRatio: 0.34, saturationAvg: 39, lightnessAvg: 52, warmthScore: 0.5, hueVariance: 560, formalityRange: 0, dominantTraits: ["casual","minimalist"], label: "Casual" },
  { formality: 1.0, neutralRatio: 0.17, saturationAvg: 53, lightnessAvg: 63, warmthScore: 0.8, hueVariance: 900, formalityRange: 0, dominantTraits: ["casual","bold"], label: "Casual" },
  { formality: 1.4, neutralRatio: 0.29, saturationAvg: 43, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 660, formalityRange: 0, dominantTraits: ["casual","classic"], label: "Casual" },
  { formality: 2.0, neutralRatio: 0.41, saturationAvg: 36, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 470, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Casual" },

  // ══════════════════════════════════════════════════════════════════════════
  // COLLEGE (30 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 1.5, neutralRatio: 0.30, saturationAvg: 45, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 700, formalityRange: 0, dominantTraits: ["casual","trendy"], label: "College" },
  { formality: 2.0, neutralRatio: 0.40, saturationAvg: 40, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 550, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "College" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 50, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 800, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "College" },
  { formality: 1.5, neutralRatio: 0.35, saturationAvg: 48, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 750, formalityRange: 0, dominantTraits: ["trendy","casual"], label: "College" },
  { formality: 2.0, neutralRatio: 0.38, saturationAvg: 42, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 600, formalityRange: 1, dominantTraits: ["casual","preppy"], label: "College" },
  { formality: 1.0, neutralRatio: 0.22, saturationAvg: 52, lightnessAvg: 60, warmthScore: 0.6, hueVariance: 850, formalityRange: 0, dominantTraits: ["casual","edgy"], label: "College" },
  { formality: 1.5, neutralRatio: 0.28, saturationAvg: 47, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 720, formalityRange: 0, dominantTraits: ["trendy","sporty"], label: "College" },
  { formality: 2.0, neutralRatio: 0.42, saturationAvg: 38, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 520, formalityRange: 1, dominantTraits: ["casual","classic"], label: "College" },
  { formality: 1.2, neutralRatio: 0.25, saturationAvg: 50, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 800, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "College" },
  { formality: 1.8, neutralRatio: 0.35, saturationAvg: 44, lightnessAvg: 53, warmthScore: 0.5, hueVariance: 650, formalityRange: 0, dominantTraits: ["casual","trendy"], label: "College" },
  { formality: 1.5, neutralRatio: 0.30, saturationAvg: 46, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 700, formalityRange: 0, dominantTraits: ["trendy","casual"], label: "College" },
  { formality: 1.0, neutralRatio: 0.18, saturationAvg: 53, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 870, formalityRange: 0, dominantTraits: ["edgy","sporty"], label: "College" },
  { formality: 2.0, neutralRatio: 0.36, saturationAvg: 41, lightnessAvg: 51, warmthScore: 0.4, hueVariance: 570, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "College" },
  { formality: 1.5, neutralRatio: 0.32, saturationAvg: 48, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 740, formalityRange: 0, dominantTraits: ["trendy","casual"], label: "College" },
  { formality: 1.8, neutralRatio: 0.38, saturationAvg: 43, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 600, formalityRange: 0, dominantTraits: ["casual","preppy"], label: "College" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 51, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 830, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "College" },
  { formality: 1.5, neutralRatio: 0.27, saturationAvg: 47, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 730, formalityRange: 0, dominantTraits: ["trendy","sporty"], label: "College" },
  { formality: 2.0, neutralRatio: 0.40, saturationAvg: 39, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 540, formalityRange: 1, dominantTraits: ["casual","classic"], label: "College" },
  { formality: 1.3, neutralRatio: 0.24, saturationAvg: 50, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 790, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "College" },
  { formality: 1.7, neutralRatio: 0.34, saturationAvg: 44, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 660, formalityRange: 0, dominantTraits: ["casual","trendy"], label: "College" },
  { formality: 1.5, neutralRatio: 0.31, saturationAvg: 46, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 710, formalityRange: 0, dominantTraits: ["trendy","casual"], label: "College" },
  { formality: 1.0, neutralRatio: 0.19, saturationAvg: 52, lightnessAvg: 60, warmthScore: 0.6, hueVariance: 840, formalityRange: 0, dominantTraits: ["edgy","casual"], label: "College" },
  { formality: 2.0, neutralRatio: 0.37, saturationAvg: 40, lightnessAvg: 51, warmthScore: 0.4, hueVariance: 560, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "College" },
  { formality: 1.5, neutralRatio: 0.29, saturationAvg: 48, lightnessAvg: 57, warmthScore: 0.5, hueVariance: 750, formalityRange: 0, dominantTraits: ["trendy","casual"], label: "College" },
  { formality: 1.8, neutralRatio: 0.36, saturationAvg: 42, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 610, formalityRange: 0, dominantTraits: ["casual","preppy"], label: "College" },
  { formality: 1.0, neutralRatio: 0.21, saturationAvg: 51, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 820, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "College" },
  { formality: 1.5, neutralRatio: 0.28, saturationAvg: 47, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 720, formalityRange: 0, dominantTraits: ["trendy","sporty"], label: "College" },
  { formality: 2.0, neutralRatio: 0.39, saturationAvg: 39, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 530, formalityRange: 1, dominantTraits: ["casual","classic"], label: "College" },
  { formality: 1.2, neutralRatio: 0.23, saturationAvg: 50, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 810, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "College" },
  { formality: 1.7, neutralRatio: 0.33, saturationAvg: 45, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 680, formalityRange: 0, dominantTraits: ["casual","trendy"], label: "College" },

  // ══════════════════════════════════════════════════════════════════════════
  // PARTY (30 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 2.0, neutralRatio: 0.20, saturationAvg: 70, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1200, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Party" },
  { formality: 3.0, neutralRatio: 0.30, saturationAvg: 65, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 1000, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.10, saturationAvg: 75, lightnessAvg: 52, warmthScore: 0.7, hueVariance: 1400, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 2.0, neutralRatio: 0.15, saturationAvg: 72, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1300, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Party" },
  { formality: 3.0, neutralRatio: 0.25, saturationAvg: 68, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 1100, formalityRange: 1, dominantTraits: ["trendy","elegant"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.18, saturationAvg: 73, lightnessAvg: 51, warmthScore: 0.6, hueVariance: 1350, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Party" },
  { formality: 2.0, neutralRatio: 0.22, saturationAvg: 69, lightnessAvg: 49, warmthScore: 0.5, hueVariance: 1150, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Party" },
  { formality: 3.0, neutralRatio: 0.28, saturationAvg: 66, lightnessAvg: 47, warmthScore: 0.5, hueVariance: 1050, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.12, saturationAvg: 76, lightnessAvg: 53, warmthScore: 0.7, hueVariance: 1450, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Party" },
  { formality: 2.0, neutralRatio: 0.20, saturationAvg: 71, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1250, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 3.0, neutralRatio: 0.25, saturationAvg: 67, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 1080, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.15, saturationAvg: 74, lightnessAvg: 52, warmthScore: 0.7, hueVariance: 1380, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 2.0, neutralRatio: 0.18, saturationAvg: 70, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1200, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Party" },
  { formality: 2.8, neutralRatio: 0.22, saturationAvg: 68, lightnessAvg: 49, warmthScore: 0.5, hueVariance: 1120, formalityRange: 1, dominantTraits: ["trendy","elegant"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.14, saturationAvg: 75, lightnessAvg: 52, warmthScore: 0.7, hueVariance: 1400, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Party" },
  { formality: 2.2, neutralRatio: 0.20, saturationAvg: 71, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1250, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Party" },
  { formality: 3.0, neutralRatio: 0.27, saturationAvg: 66, lightnessAvg: 47, warmthScore: 0.5, hueVariance: 1060, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.16, saturationAvg: 73, lightnessAvg: 51, warmthScore: 0.6, hueVariance: 1320, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Party" },
  { formality: 2.0, neutralRatio: 0.19, saturationAvg: 70, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1220, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Party" },
  { formality: 2.8, neutralRatio: 0.24, saturationAvg: 67, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 1090, formalityRange: 1, dominantTraits: ["trendy","elegant"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.13, saturationAvg: 74, lightnessAvg: 52, warmthScore: 0.7, hueVariance: 1380, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Party" },
  { formality: 2.2, neutralRatio: 0.21, saturationAvg: 70, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1230, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 3.0, neutralRatio: 0.26, saturationAvg: 67, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 1070, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.17, saturationAvg: 73, lightnessAvg: 51, warmthScore: 0.6, hueVariance: 1340, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 2.0, neutralRatio: 0.20, saturationAvg: 71, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1260, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Party" },
  { formality: 2.8, neutralRatio: 0.23, saturationAvg: 68, lightnessAvg: 49, warmthScore: 0.5, hueVariance: 1110, formalityRange: 1, dominantTraits: ["trendy","elegant"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.11, saturationAvg: 76, lightnessAvg: 53, warmthScore: 0.7, hueVariance: 1460, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Party" },
  { formality: 2.2, neutralRatio: 0.19, saturationAvg: 70, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 1240, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Party" },
  { formality: 3.0, neutralRatio: 0.28, saturationAvg: 65, lightnessAvg: 47, warmthScore: 0.5, hueVariance: 1040, formalityRange: 1, dominantTraits: ["trendy","bold"], label: "Party" },
  { formality: 2.5, neutralRatio: 0.15, saturationAvg: 74, lightnessAvg: 52, warmthScore: 0.7, hueVariance: 1390, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Party" },

  // ══════════════════════════════════════════════════════════════════════════
  // DATE NIGHT (30 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 3.0, neutralRatio: 0.40, saturationAvg: 45, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 3.5, neutralRatio: 0.50, saturationAvg: 40, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 400, formalityRange: 1, dominantTraits: ["romantic","elegant"], label: "Date Night" },
  { formality: 2.5, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 600, formalityRange: 1, dominantTraits: ["trendy","romantic"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.35, saturationAvg: 48, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 520, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 3.5, neutralRatio: 0.45, saturationAvg: 42, lightnessAvg: 46, warmthScore: 0.4, hueVariance: 420, formalityRange: 1, dominantTraits: ["romantic","classic"], label: "Date Night" },
  { formality: 2.5, neutralRatio: 0.28, saturationAvg: 52, lightnessAvg: 51, warmthScore: 0.6, hueVariance: 620, formalityRange: 1, dominantTraits: ["trendy","elegant"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.38, saturationAvg: 46, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 480, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 3.5, neutralRatio: 0.48, saturationAvg: 41, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 410, formalityRange: 1, dominantTraits: ["romantic","elegant"], label: "Date Night" },
  { formality: 2.8, neutralRatio: 0.32, saturationAvg: 49, lightnessAvg: 50, warmthScore: 0.5, hueVariance: 560, formalityRange: 1, dominantTraits: ["trendy","romantic"], label: "Date Night" },
  { formality: 3.2, neutralRatio: 0.42, saturationAvg: 44, lightnessAvg: 47, warmthScore: 0.4, hueVariance: 450, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.36, saturationAvg: 47, lightnessAvg: 49, warmthScore: 0.5, hueVariance: 510, formalityRange: 1, dominantTraits: ["romantic","elegant"], label: "Date Night" },
  { formality: 3.5, neutralRatio: 0.46, saturationAvg: 41, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 400, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 2.5, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 600, formalityRange: 1, dominantTraits: ["trendy","romantic"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.40, saturationAvg: 45, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 490, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 3.3, neutralRatio: 0.44, saturationAvg: 43, lightnessAvg: 46, warmthScore: 0.4, hueVariance: 440, formalityRange: 1, dominantTraits: ["romantic","classic"], label: "Date Night" },
  { formality: 2.8, neutralRatio: 0.33, saturationAvg: 48, lightnessAvg: 49, warmthScore: 0.5, hueVariance: 540, formalityRange: 1, dominantTraits: ["trendy","elegant"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.37, saturationAvg: 46, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 3.5, neutralRatio: 0.47, saturationAvg: 42, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 415, formalityRange: 1, dominantTraits: ["romantic","elegant"], label: "Date Night" },
  { formality: 2.5, neutralRatio: 0.29, saturationAvg: 51, lightnessAvg: 51, warmthScore: 0.6, hueVariance: 610, formalityRange: 1, dominantTraits: ["trendy","romantic"], label: "Date Night" },
  { formality: 3.2, neutralRatio: 0.41, saturationAvg: 44, lightnessAvg: 47, warmthScore: 0.4, hueVariance: 460, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.38, saturationAvg: 46, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["romantic","elegant"], label: "Date Night" },
  { formality: 3.5, neutralRatio: 0.49, saturationAvg: 40, lightnessAvg: 44, warmthScore: 0.4, hueVariance: 390, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 2.8, neutralRatio: 0.31, saturationAvg: 49, lightnessAvg: 50, warmthScore: 0.5, hueVariance: 570, formalityRange: 1, dominantTraits: ["trendy","romantic"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.39, saturationAvg: 45, lightnessAvg: 48, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 3.3, neutralRatio: 0.43, saturationAvg: 43, lightnessAvg: 46, warmthScore: 0.4, hueVariance: 440, formalityRange: 1, dominantTraits: ["romantic","classic"], label: "Date Night" },
  { formality: 2.5, neutralRatio: 0.27, saturationAvg: 52, lightnessAvg: 52, warmthScore: 0.6, hueVariance: 630, formalityRange: 1, dominantTraits: ["trendy","elegant"], label: "Date Night" },
  { formality: 3.0, neutralRatio: 0.36, saturationAvg: 47, lightnessAvg: 49, warmthScore: 0.5, hueVariance: 510, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Date Night" },
  { formality: 3.4, neutralRatio: 0.45, saturationAvg: 42, lightnessAvg: 46, warmthScore: 0.4, hueVariance: 430, formalityRange: 1, dominantTraits: ["romantic","elegant"], label: "Date Night" },
  { formality: 2.8, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 50, warmthScore: 0.6, hueVariance: 590, formalityRange: 1, dominantTraits: ["trendy","romantic"], label: "Date Night" },
  { formality: 3.2, neutralRatio: 0.40, saturationAvg: 44, lightnessAvg: 47, warmthScore: 0.5, hueVariance: 470, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Date Night" },

  // ══════════════════════════════════════════════════════════════════════════
  // FORMAL (25 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 5.0, neutralRatio: 0.50, saturationAvg: 20, lightnessAvg: 35, warmthScore: 0.2, hueVariance: 50, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Formal" },
  { formality: 4.5, neutralRatio: 0.60, saturationAvg: 25, lightnessAvg: 38, warmthScore: 0.2, hueVariance: 80, formalityRange: 0, dominantTraits: ["elegant","classic"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.70, saturationAvg: 15, lightnessAvg: 32, warmthScore: 0.1, hueVariance: 30, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Formal" },
  { formality: 4.5, neutralRatio: 0.55, saturationAvg: 22, lightnessAvg: 36, warmthScore: 0.2, hueVariance: 60, formalityRange: 0, dominantTraits: ["elegant","formal"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.65, saturationAvg: 18, lightnessAvg: 33, warmthScore: 0.1, hueVariance: 40, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Formal" },
  { formality: 4.8, neutralRatio: 0.58, saturationAvg: 20, lightnessAvg: 35, warmthScore: 0.2, hueVariance: 55, formalityRange: 0, dominantTraits: ["elegant","formal"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.72, saturationAvg: 14, lightnessAvg: 30, warmthScore: 0.1, hueVariance: 25, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Formal" },
  { formality: 4.5, neutralRatio: 0.52, saturationAvg: 24, lightnessAvg: 37, warmthScore: 0.2, hueVariance: 70, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Formal" },
  { formality: 4.8, neutralRatio: 0.62, saturationAvg: 19, lightnessAvg: 34, warmthScore: 0.1, hueVariance: 45, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.68, saturationAvg: 16, lightnessAvg: 32, warmthScore: 0.1, hueVariance: 35, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Formal" },
  { formality: 4.5, neutralRatio: 0.54, saturationAvg: 23, lightnessAvg: 37, warmthScore: 0.2, hueVariance: 65, formalityRange: 0, dominantTraits: ["elegant","formal"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.70, saturationAvg: 15, lightnessAvg: 31, warmthScore: 0.1, hueVariance: 30, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Formal" },
  { formality: 4.7, neutralRatio: 0.57, saturationAvg: 21, lightnessAvg: 35, warmthScore: 0.2, hueVariance: 50, formalityRange: 0, dominantTraits: ["elegant","classic"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.66, saturationAvg: 17, lightnessAvg: 33, warmthScore: 0.1, hueVariance: 38, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Formal" },
  { formality: 4.5, neutralRatio: 0.53, saturationAvg: 24, lightnessAvg: 38, warmthScore: 0.2, hueVariance: 72, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Formal" },
  { formality: 4.9, neutralRatio: 0.60, saturationAvg: 20, lightnessAvg: 34, warmthScore: 0.1, hueVariance: 48, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.71, saturationAvg: 14, lightnessAvg: 30, warmthScore: 0.1, hueVariance: 28, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Formal" },
  { formality: 4.6, neutralRatio: 0.55, saturationAvg: 22, lightnessAvg: 36, warmthScore: 0.2, hueVariance: 58, formalityRange: 0, dominantTraits: ["elegant","classic"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.67, saturationAvg: 16, lightnessAvg: 32, warmthScore: 0.1, hueVariance: 33, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Formal" },
  { formality: 4.5, neutralRatio: 0.51, saturationAvg: 25, lightnessAvg: 38, warmthScore: 0.2, hueVariance: 75, formalityRange: 0, dominantTraits: ["elegant","formal"], label: "Formal" },
  { formality: 4.8, neutralRatio: 0.60, saturationAvg: 19, lightnessAvg: 34, warmthScore: 0.2, hueVariance: 50, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.73, saturationAvg: 13, lightnessAvg: 29, warmthScore: 0.1, hueVariance: 22, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Formal" },
  { formality: 4.6, neutralRatio: 0.56, saturationAvg: 21, lightnessAvg: 36, warmthScore: 0.2, hueVariance: 55, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Formal" },
  { formality: 5.0, neutralRatio: 0.69, saturationAvg: 15, lightnessAvg: 31, warmthScore: 0.1, hueVariance: 32, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Formal" },
  { formality: 4.7, neutralRatio: 0.58, saturationAvg: 20, lightnessAvg: 35, warmthScore: 0.2, hueVariance: 52, formalityRange: 0, dominantTraits: ["elegant","formal"], label: "Formal" },

  // ══════════════════════════════════════════════════════════════════════════
  // WEDDING (25 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 5.0, neutralRatio: 0.40, saturationAvg: 30, lightnessAvg: 55, warmthScore: 0.4, hueVariance: 150, formalityRange: 0, dominantTraits: ["formal","romantic"], label: "Wedding" },
  { formality: 4.5, neutralRatio: 0.35, saturationAvg: 35, lightnessAvg: 58, warmthScore: 0.5, hueVariance: 200, formalityRange: 0, dominantTraits: ["elegant","romantic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.30, saturationAvg: 38, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 250, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Wedding" },
  { formality: 4.5, neutralRatio: 0.38, saturationAvg: 33, lightnessAvg: 56, warmthScore: 0.4, hueVariance: 180, formalityRange: 0, dominantTraits: ["romantic","classic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.42, saturationAvg: 28, lightnessAvg: 52, warmthScore: 0.3, hueVariance: 120, formalityRange: 0, dominantTraits: ["formal","romantic"], label: "Wedding" },
  { formality: 4.8, neutralRatio: 0.36, saturationAvg: 34, lightnessAvg: 57, warmthScore: 0.5, hueVariance: 190, formalityRange: 0, dominantTraits: ["elegant","romantic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.32, saturationAvg: 36, lightnessAvg: 59, warmthScore: 0.5, hueVariance: 220, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Wedding" },
  { formality: 4.5, neutralRatio: 0.40, saturationAvg: 31, lightnessAvg: 54, warmthScore: 0.4, hueVariance: 160, formalityRange: 0, dominantTraits: ["romantic","elegant"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.38, saturationAvg: 32, lightnessAvg: 56, warmthScore: 0.4, hueVariance: 170, formalityRange: 0, dominantTraits: ["formal","romantic"], label: "Wedding" },
  { formality: 4.8, neutralRatio: 0.34, saturationAvg: 35, lightnessAvg: 58, warmthScore: 0.5, hueVariance: 200, formalityRange: 0, dominantTraits: ["elegant","classic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.41, saturationAvg: 29, lightnessAvg: 53, warmthScore: 0.3, hueVariance: 130, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Wedding" },
  { formality: 4.5, neutralRatio: 0.37, saturationAvg: 33, lightnessAvg: 56, warmthScore: 0.4, hueVariance: 180, formalityRange: 0, dominantTraits: ["romantic","elegant"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.33, saturationAvg: 37, lightnessAvg: 59, warmthScore: 0.5, hueVariance: 230, formalityRange: 0, dominantTraits: ["formal","romantic"], label: "Wedding" },
  { formality: 4.7, neutralRatio: 0.39, saturationAvg: 32, lightnessAvg: 55, warmthScore: 0.4, hueVariance: 165, formalityRange: 0, dominantTraits: ["elegant","romantic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.35, saturationAvg: 35, lightnessAvg: 58, warmthScore: 0.5, hueVariance: 210, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Wedding" },
  { formality: 4.5, neutralRatio: 0.36, saturationAvg: 34, lightnessAvg: 57, warmthScore: 0.5, hueVariance: 190, formalityRange: 0, dominantTraits: ["romantic","classic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.40, saturationAvg: 30, lightnessAvg: 54, warmthScore: 0.4, hueVariance: 145, formalityRange: 0, dominantTraits: ["formal","romantic"], label: "Wedding" },
  { formality: 4.8, neutralRatio: 0.34, saturationAvg: 36, lightnessAvg: 58, warmthScore: 0.5, hueVariance: 210, formalityRange: 0, dominantTraits: ["elegant","romantic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.31, saturationAvg: 37, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 240, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Wedding" },
  { formality: 4.5, neutralRatio: 0.38, saturationAvg: 33, lightnessAvg: 55, warmthScore: 0.4, hueVariance: 175, formalityRange: 0, dominantTraits: ["romantic","elegant"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.42, saturationAvg: 28, lightnessAvg: 52, warmthScore: 0.3, hueVariance: 115, formalityRange: 0, dominantTraits: ["formal","romantic"], label: "Wedding" },
  { formality: 4.7, neutralRatio: 0.36, saturationAvg: 34, lightnessAvg: 57, warmthScore: 0.4, hueVariance: 185, formalityRange: 0, dominantTraits: ["elegant","classic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.33, saturationAvg: 36, lightnessAvg: 59, warmthScore: 0.5, hueVariance: 225, formalityRange: 0, dominantTraits: ["formal","romantic"], label: "Wedding" },
  { formality: 4.8, neutralRatio: 0.37, saturationAvg: 32, lightnessAvg: 56, warmthScore: 0.4, hueVariance: 170, formalityRange: 0, dominantTraits: ["elegant","romantic"], label: "Wedding" },
  { formality: 5.0, neutralRatio: 0.39, saturationAvg: 31, lightnessAvg: 55, warmthScore: 0.4, hueVariance: 155, formalityRange: 0, dominantTraits: ["formal","elegant"], label: "Wedding" },

  // ══════════════════════════════════════════════════════════════════════════
  // SPORTS (25 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 55, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 900, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 800, formalityRange: 0, dominantTraits: ["sporty"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.15, saturationAvg: 60, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 1000, formalityRange: 0, dominantTraits: ["sporty","bold"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.25, saturationAvg: 52, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 850, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.18, saturationAvg: 58, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 950, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.28, saturationAvg: 51, lightnessAvg: 53, warmthScore: 0.4, hueVariance: 820, formalityRange: 0, dominantTraits: ["sporty"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.12, saturationAvg: 62, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 1050, formalityRange: 0, dominantTraits: ["sporty","bold"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.22, saturationAvg: 54, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 880, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.16, saturationAvg: 59, lightnessAvg: 57, warmthScore: 0.6, hueVariance: 970, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.26, saturationAvg: 52, lightnessAvg: 53, warmthScore: 0.4, hueVariance: 830, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 56, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 910, formalityRange: 0, dominantTraits: ["sporty"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.14, saturationAvg: 61, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 1020, formalityRange: 0, dominantTraits: ["sporty","bold"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.24, saturationAvg: 53, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 860, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.19, saturationAvg: 57, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 940, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.27, saturationAvg: 51, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 810, formalityRange: 0, dominantTraits: ["sporty"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.13, saturationAvg: 63, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 1060, formalityRange: 0, dominantTraits: ["sporty","bold"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.21, saturationAvg: 55, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 890, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.17, saturationAvg: 58, lightnessAvg: 57, warmthScore: 0.6, hueVariance: 960, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.25, saturationAvg: 52, lightnessAvg: 53, warmthScore: 0.4, hueVariance: 840, formalityRange: 0, dominantTraits: ["sporty"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.15, saturationAvg: 60, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 1000, formalityRange: 0, dominantTraits: ["sporty","bold"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.23, saturationAvg: 54, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 870, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.18, saturationAvg: 57, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 930, formalityRange: 0, dominantTraits: ["sporty","edgy"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.29, saturationAvg: 50, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 800, formalityRange: 0, dominantTraits: ["sporty"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.11, saturationAvg: 64, lightnessAvg: 61, warmthScore: 0.7, hueVariance: 1080, formalityRange: 0, dominantTraits: ["sporty","bold"], label: "Sports" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 56, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 900, formalityRange: 0, dominantTraits: ["sporty","casual"], label: "Sports" },

  // ══════════════════════════════════════════════════════════════════════════
  // FESTIVAL (25 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 1.5, neutralRatio: 0.20, saturationAvg: 55, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 1200, formalityRange: 0, dominantTraits: ["bohemian","trendy"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 1000, formalityRange: 1, dominantTraits: ["bohemian","romantic"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.15, saturationAvg: 58, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 1400, formalityRange: 0, dominantTraits: ["bohemian","bold"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.18, saturationAvg: 56, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 1300, formalityRange: 0, dominantTraits: ["bohemian","trendy"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.25, saturationAvg: 52, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 1100, formalityRange: 1, dominantTraits: ["bohemian","casual"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.12, saturationAvg: 60, lightnessAvg: 62, warmthScore: 0.7, hueVariance: 1500, formalityRange: 0, dominantTraits: ["bohemian","bold"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.22, saturationAvg: 54, lightnessAvg: 57, warmthScore: 0.6, hueVariance: 1150, formalityRange: 0, dominantTraits: ["trendy","bohemian"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.28, saturationAvg: 51, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 1050, formalityRange: 1, dominantTraits: ["bohemian","romantic"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.16, saturationAvg: 57, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 1350, formalityRange: 0, dominantTraits: ["bohemian","trendy"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.20, saturationAvg: 55, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 1200, formalityRange: 0, dominantTraits: ["trendy","bohemian"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.26, saturationAvg: 52, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 1080, formalityRange: 1, dominantTraits: ["bohemian","casual"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.14, saturationAvg: 59, lightnessAvg: 61, warmthScore: 0.7, hueVariance: 1420, formalityRange: 0, dominantTraits: ["bohemian","bold"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.19, saturationAvg: 56, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 1250, formalityRange: 0, dominantTraits: ["trendy","bohemian"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.27, saturationAvg: 51, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 1060, formalityRange: 1, dominantTraits: ["bohemian","romantic"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.17, saturationAvg: 57, lightnessAvg: 60, warmthScore: 0.6, hueVariance: 1320, formalityRange: 0, dominantTraits: ["bohemian","trendy"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.21, saturationAvg: 54, lightnessAvg: 57, warmthScore: 0.6, hueVariance: 1180, formalityRange: 0, dominantTraits: ["trendy","bohemian"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.29, saturationAvg: 50, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 1020, formalityRange: 1, dominantTraits: ["bohemian","casual"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.13, saturationAvg: 60, lightnessAvg: 62, warmthScore: 0.7, hueVariance: 1480, formalityRange: 0, dominantTraits: ["bohemian","bold"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.20, saturationAvg: 55, lightnessAvg: 58, warmthScore: 0.6, hueVariance: 1210, formalityRange: 0, dominantTraits: ["bohemian","trendy"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.25, saturationAvg: 52, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 1090, formalityRange: 1, dominantTraits: ["bohemian","romantic"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.15, saturationAvg: 58, lightnessAvg: 60, warmthScore: 0.7, hueVariance: 1380, formalityRange: 0, dominantTraits: ["bohemian","bold"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.18, saturationAvg: 56, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 1280, formalityRange: 0, dominantTraits: ["trendy","bohemian"], label: "Festival" },
  { formality: 2.0, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 1000, formalityRange: 1, dominantTraits: ["bohemian","casual"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.16, saturationAvg: 57, lightnessAvg: 59, warmthScore: 0.6, hueVariance: 1340, formalityRange: 0, dominantTraits: ["bohemian","trendy"], label: "Festival" },
  { formality: 1.5, neutralRatio: 0.22, saturationAvg: 54, lightnessAvg: 57, warmthScore: 0.6, hueVariance: 1160, formalityRange: 0, dominantTraits: ["trendy","bohemian"], label: "Festival" },

  // ══════════════════════════════════════════════════════════════════════════
  // BRUNCH (25 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 2.5, neutralRatio: 0.35, saturationAvg: 42, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["casual","elegant"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.30, saturationAvg: 45, lightnessAvg: 62, warmthScore: 0.6, hueVariance: 600, formalityRange: 1, dominantTraits: ["casual","romantic"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.40, saturationAvg: 38, lightnessAvg: 58, warmthScore: 0.5, hueVariance: 450, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.32, saturationAvg: 44, lightnessAvg: 61, warmthScore: 0.6, hueVariance: 550, formalityRange: 1, dominantTraits: ["casual","trendy"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.38, saturationAvg: 40, lightnessAvg: 59, warmthScore: 0.5, hueVariance: 480, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.28, saturationAvg: 46, lightnessAvg: 63, warmthScore: 0.6, hueVariance: 620, formalityRange: 1, dominantTraits: ["casual","romantic"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.36, saturationAvg: 41, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 490, formalityRange: 1, dominantTraits: ["casual","elegant"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.30, saturationAvg: 45, lightnessAvg: 62, warmthScore: 0.6, hueVariance: 580, formalityRange: 1, dominantTraits: ["casual","trendy"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.37, saturationAvg: 39, lightnessAvg: 58, warmthScore: 0.5, hueVariance: 470, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.33, saturationAvg: 43, lightnessAvg: 61, warmthScore: 0.6, hueVariance: 540, formalityRange: 1, dominantTraits: ["casual","romantic"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.35, saturationAvg: 42, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["casual","elegant"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.29, saturationAvg: 46, lightnessAvg: 63, warmthScore: 0.6, hueVariance: 610, formalityRange: 1, dominantTraits: ["casual","trendy"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.39, saturationAvg: 39, lightnessAvg: 58, warmthScore: 0.5, hueVariance: 460, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.31, saturationAvg: 44, lightnessAvg: 62, warmthScore: 0.6, hueVariance: 560, formalityRange: 1, dominantTraits: ["casual","romantic"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.36, saturationAvg: 41, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 490, formalityRange: 1, dominantTraits: ["casual","elegant"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.30, saturationAvg: 45, lightnessAvg: 62, warmthScore: 0.6, hueVariance: 590, formalityRange: 1, dominantTraits: ["casual","trendy"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.38, saturationAvg: 40, lightnessAvg: 59, warmthScore: 0.5, hueVariance: 475, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.32, saturationAvg: 44, lightnessAvg: 61, warmthScore: 0.6, hueVariance: 550, formalityRange: 1, dominantTraits: ["casual","romantic"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.35, saturationAvg: 42, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["casual","elegant"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.28, saturationAvg: 46, lightnessAvg: 63, warmthScore: 0.6, hueVariance: 630, formalityRange: 1, dominantTraits: ["casual","trendy"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.37, saturationAvg: 40, lightnessAvg: 59, warmthScore: 0.5, hueVariance: 480, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.31, saturationAvg: 44, lightnessAvg: 61, warmthScore: 0.6, hueVariance: 560, formalityRange: 1, dominantTraits: ["casual","romantic"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.36, saturationAvg: 41, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 495, formalityRange: 1, dominantTraits: ["casual","elegant"], label: "Brunch" },
  { formality: 2.0, neutralRatio: 0.30, saturationAvg: 45, lightnessAvg: 62, warmthScore: 0.6, hueVariance: 580, formalityRange: 1, dominantTraits: ["casual","trendy"], label: "Brunch" },
  { formality: 2.5, neutralRatio: 0.34, saturationAvg: 42, lightnessAvg: 60, warmthScore: 0.5, hueVariance: 505, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Brunch" },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS CASUAL (25 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 3.0, neutralRatio: 0.45, saturationAvg: 32, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 350, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 2.5, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 400, formalityRange: 1, dominantTraits: ["preppy","classic"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.50, saturationAvg: 30, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 300, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Business Casual" },
  { formality: 2.5, neutralRatio: 0.42, saturationAvg: 34, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 380, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.48, saturationAvg: 31, lightnessAvg: 47, warmthScore: 0.3, hueVariance: 320, formalityRange: 1, dominantTraits: ["preppy","classic"], label: "Business Casual" },
  { formality: 2.5, neutralRatio: 0.38, saturationAvg: 36, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 420, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.46, saturationAvg: 32, lightnessAvg: 48, warmthScore: 0.3, hueVariance: 340, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Business Casual" },
  { formality: 2.8, neutralRatio: 0.43, saturationAvg: 33, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 370, formalityRange: 1, dominantTraits: ["preppy","classic"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.50, saturationAvg: 29, lightnessAvg: 45, warmthScore: 0.3, hueVariance: 280, formalityRange: 1, dominantTraits: ["classic","minimalist"], label: "Business Casual" },
  { formality: 2.5, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 400, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.47, saturationAvg: 31, lightnessAvg: 47, warmthScore: 0.3, hueVariance: 330, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Business Casual" },
  { formality: 2.8, neutralRatio: 0.42, saturationAvg: 34, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 380, formalityRange: 1, dominantTraits: ["preppy","classic"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.48, saturationAvg: 30, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 310, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 2.5, neutralRatio: 0.39, saturationAvg: 36, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 410, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.45, saturationAvg: 32, lightnessAvg: 48, warmthScore: 0.3, hueVariance: 350, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Business Casual" },
  { formality: 2.8, neutralRatio: 0.41, saturationAvg: 34, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 375, formalityRange: 1, dominantTraits: ["preppy","classic"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.49, saturationAvg: 30, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 300, formalityRange: 1, dominantTraits: ["classic","minimalist"], label: "Business Casual" },
  { formality: 2.5, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 50, warmthScore: 0.4, hueVariance: 400, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.46, saturationAvg: 32, lightnessAvg: 47, warmthScore: 0.3, hueVariance: 340, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Business Casual" },
  { formality: 2.8, neutralRatio: 0.43, saturationAvg: 33, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 365, formalityRange: 1, dominantTraits: ["preppy","classic"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.47, saturationAvg: 31, lightnessAvg: 47, warmthScore: 0.3, hueVariance: 325, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 2.5, neutralRatio: 0.38, saturationAvg: 36, lightnessAvg: 51, warmthScore: 0.5, hueVariance: 430, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.45, saturationAvg: 32, lightnessAvg: 48, warmthScore: 0.3, hueVariance: 345, formalityRange: 1, dominantTraits: ["classic","elegant"], label: "Business Casual" },
  { formality: 2.8, neutralRatio: 0.42, saturationAvg: 34, lightnessAvg: 49, warmthScore: 0.4, hueVariance: 380, formalityRange: 1, dominantTraits: ["preppy","classic"], label: "Business Casual" },
  { formality: 3.0, neutralRatio: 0.50, saturationAvg: 29, lightnessAvg: 45, warmthScore: 0.3, hueVariance: 290, formalityRange: 1, dominantTraits: ["classic","minimalist"], label: "Business Casual" },

  // ══════════════════════════════════════════════════════════════════════════
  // STREETWEAR (25 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 1.5, neutralRatio: 0.35, saturationAvg: 45, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 900, formalityRange: 1, dominantTraits: ["edgy","casual"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 45, warmthScore: 0.3, hueVariance: 1000, formalityRange: 0, dominantTraits: ["edgy","bold"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.40, saturationAvg: 42, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 800, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.32, saturationAvg: 48, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 950, formalityRange: 0, dominantTraits: ["bold","edgy"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.38, saturationAvg: 44, lightnessAvg: 47, warmthScore: 0.4, hueVariance: 850, formalityRange: 1, dominantTraits: ["edgy","casual"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.28, saturationAvg: 52, lightnessAvg: 46, warmthScore: 0.4, hueVariance: 1050, formalityRange: 0, dominantTraits: ["edgy","bold"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.36, saturationAvg: 43, lightnessAvg: 47, warmthScore: 0.3, hueVariance: 880, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.34, saturationAvg: 47, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 920, formalityRange: 0, dominantTraits: ["bold","edgy"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.40, saturationAvg: 42, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 800, formalityRange: 1, dominantTraits: ["edgy","casual"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 1000, formalityRange: 0, dominantTraits: ["edgy","bold"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.37, saturationAvg: 44, lightnessAvg: 47, warmthScore: 0.4, hueVariance: 860, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.31, saturationAvg: 49, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 970, formalityRange: 0, dominantTraits: ["bold","edgy"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.39, saturationAvg: 43, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 830, formalityRange: 1, dominantTraits: ["edgy","casual"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.29, saturationAvg: 51, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 1020, formalityRange: 0, dominantTraits: ["edgy","bold"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.35, saturationAvg: 45, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 900, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.33, saturationAvg: 48, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 940, formalityRange: 0, dominantTraits: ["bold","edgy"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.38, saturationAvg: 43, lightnessAvg: 47, warmthScore: 0.3, hueVariance: 850, formalityRange: 1, dominantTraits: ["edgy","casual"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.30, saturationAvg: 50, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 990, formalityRange: 0, dominantTraits: ["edgy","bold"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.36, saturationAvg: 44, lightnessAvg: 47, warmthScore: 0.4, hueVariance: 870, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.32, saturationAvg: 49, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 960, formalityRange: 0, dominantTraits: ["bold","edgy"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.40, saturationAvg: 42, lightnessAvg: 46, warmthScore: 0.3, hueVariance: 810, formalityRange: 1, dominantTraits: ["edgy","casual"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.28, saturationAvg: 52, lightnessAvg: 46, warmthScore: 0.4, hueVariance: 1040, formalityRange: 0, dominantTraits: ["edgy","bold"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.37, saturationAvg: 43, lightnessAvg: 47, warmthScore: 0.3, hueVariance: 840, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Streetwear" },
  { formality: 1.0, neutralRatio: 0.34, saturationAvg: 47, lightnessAvg: 44, warmthScore: 0.3, hueVariance: 930, formalityRange: 0, dominantTraits: ["bold","edgy"], label: "Streetwear" },
  { formality: 1.5, neutralRatio: 0.35, saturationAvg: 45, lightnessAvg: 48, warmthScore: 0.4, hueVariance: 900, formalityRange: 1, dominantTraits: ["edgy","casual"], label: "Streetwear" },

  // ══════════════════════════════════════════════════════════════════════════
  // COCKTAIL (20 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 3.5, neutralRatio: 0.35, saturationAvg: 55, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 600, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Cocktail" },
  { formality: 4.0, neutralRatio: 0.40, saturationAvg: 50, lightnessAvg: 42, warmthScore: 0.3, hueVariance: 500, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.30, saturationAvg: 58, lightnessAvg: 46, warmthScore: 0.5, hueVariance: 650, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Cocktail" },
  { formality: 4.0, neutralRatio: 0.38, saturationAvg: 52, lightnessAvg: 43, warmthScore: 0.4, hueVariance: 520, formalityRange: 1, dominantTraits: ["elegant","trendy"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.33, saturationAvg: 56, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 620, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Cocktail" },
  { formality: 4.0, neutralRatio: 0.42, saturationAvg: 48, lightnessAvg: 41, warmthScore: 0.3, hueVariance: 480, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.32, saturationAvg: 57, lightnessAvg: 46, warmthScore: 0.5, hueVariance: 640, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Cocktail" },
  { formality: 3.8, neutralRatio: 0.36, saturationAvg: 54, lightnessAvg: 44, warmthScore: 0.4, hueVariance: 560, formalityRange: 1, dominantTraits: ["elegant","trendy"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.34, saturationAvg: 55, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 600, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Cocktail" },
  { formality: 4.0, neutralRatio: 0.40, saturationAvg: 50, lightnessAvg: 42, warmthScore: 0.3, hueVariance: 510, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.31, saturationAvg: 57, lightnessAvg: 46, warmthScore: 0.5, hueVariance: 640, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Cocktail" },
  { formality: 3.8, neutralRatio: 0.37, saturationAvg: 53, lightnessAvg: 44, warmthScore: 0.4, hueVariance: 550, formalityRange: 1, dominantTraits: ["elegant","trendy"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.35, saturationAvg: 55, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 610, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Cocktail" },
  { formality: 4.0, neutralRatio: 0.39, saturationAvg: 51, lightnessAvg: 43, warmthScore: 0.3, hueVariance: 510, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.30, saturationAvg: 58, lightnessAvg: 46, warmthScore: 0.5, hueVariance: 660, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Cocktail" },
  { formality: 3.8, neutralRatio: 0.36, saturationAvg: 54, lightnessAvg: 44, warmthScore: 0.4, hueVariance: 560, formalityRange: 1, dominantTraits: ["elegant","trendy"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.33, saturationAvg: 56, lightnessAvg: 45, warmthScore: 0.4, hueVariance: 620, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Cocktail" },
  { formality: 4.0, neutralRatio: 0.41, saturationAvg: 49, lightnessAvg: 42, warmthScore: 0.3, hueVariance: 490, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Cocktail" },
  { formality: 3.5, neutralRatio: 0.32, saturationAvg: 57, lightnessAvg: 46, warmthScore: 0.5, hueVariance: 640, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Cocktail" },
  { formality: 3.8, neutralRatio: 0.38, saturationAvg: 53, lightnessAvg: 43, warmthScore: 0.4, hueVariance: 540, formalityRange: 1, dominantTraits: ["elegant","trendy"], label: "Cocktail" },

  // ══════════════════════════════════════════════════════════════════════════
  // INTERVIEW (20 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 4.5, neutralRatio: 0.65, saturationAvg: 18, lightnessAvg: 38, warmthScore: 0.2, hueVariance: 80, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.60, saturationAvg: 22, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 120, formalityRange: 0, dominantTraits: ["classic","formal"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.70, saturationAvg: 15, lightnessAvg: 36, warmthScore: 0.1, hueVariance: 50, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.58, saturationAvg: 24, lightnessAvg: 42, warmthScore: 0.2, hueVariance: 140, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.68, saturationAvg: 16, lightnessAvg: 37, warmthScore: 0.1, hueVariance: 60, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.62, saturationAvg: 20, lightnessAvg: 39, warmthScore: 0.2, hueVariance: 100, formalityRange: 0, dominantTraits: ["classic","formal"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.66, saturationAvg: 17, lightnessAvg: 37, warmthScore: 0.1, hueVariance: 70, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.60, saturationAvg: 21, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 110, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.67, saturationAvg: 17, lightnessAvg: 37, warmthScore: 0.1, hueVariance: 65, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.61, saturationAvg: 21, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 115, formalityRange: 0, dominantTraits: ["classic","formal"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.69, saturationAvg: 16, lightnessAvg: 36, warmthScore: 0.1, hueVariance: 55, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.59, saturationAvg: 23, lightnessAvg: 41, warmthScore: 0.2, hueVariance: 130, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.65, saturationAvg: 18, lightnessAvg: 38, warmthScore: 0.2, hueVariance: 85, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.60, saturationAvg: 22, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 120, formalityRange: 0, dominantTraits: ["classic","formal"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.68, saturationAvg: 16, lightnessAvg: 37, warmthScore: 0.1, hueVariance: 60, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.58, saturationAvg: 24, lightnessAvg: 42, warmthScore: 0.2, hueVariance: 135, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.66, saturationAvg: 17, lightnessAvg: 37, warmthScore: 0.1, hueVariance: 68, formalityRange: 0, dominantTraits: ["formal","classic"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.61, saturationAvg: 20, lightnessAvg: 39, warmthScore: 0.2, hueVariance: 105, formalityRange: 0, dominantTraits: ["classic","formal"], label: "Interview" },
  { formality: 4.5, neutralRatio: 0.70, saturationAvg: 15, lightnessAvg: 36, warmthScore: 0.1, hueVariance: 48, formalityRange: 0, dominantTraits: ["formal","minimalist"], label: "Interview" },
  { formality: 4.0, neutralRatio: 0.60, saturationAvg: 22, lightnessAvg: 40, warmthScore: 0.2, hueVariance: 118, formalityRange: 0, dominantTraits: ["classic","elegant"], label: "Interview" },

  // ══════════════════════════════════════════════════════════════════════════
  // ETHNIC FESTIVE (20 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 4.0, neutralRatio: 0.20, saturationAvg: 60, lightnessAvg: 55, warmthScore: 0.7, hueVariance: 800, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.25, saturationAvg: 55, lightnessAvg: 52, warmthScore: 0.6, hueVariance: 700, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.18, saturationAvg: 62, lightnessAvg: 56, warmthScore: 0.8, hueVariance: 900, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.22, saturationAvg: 58, lightnessAvg: 54, warmthScore: 0.7, hueVariance: 750, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.20, saturationAvg: 60, lightnessAvg: 55, warmthScore: 0.7, hueVariance: 800, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.24, saturationAvg: 56, lightnessAvg: 53, warmthScore: 0.6, hueVariance: 720, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.16, saturationAvg: 63, lightnessAvg: 57, warmthScore: 0.8, hueVariance: 920, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.21, saturationAvg: 58, lightnessAvg: 54, warmthScore: 0.7, hueVariance: 760, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.19, saturationAvg: 61, lightnessAvg: 56, warmthScore: 0.7, hueVariance: 810, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.23, saturationAvg: 57, lightnessAvg: 53, warmthScore: 0.6, hueVariance: 730, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.17, saturationAvg: 62, lightnessAvg: 56, warmthScore: 0.8, hueVariance: 880, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.22, saturationAvg: 58, lightnessAvg: 54, warmthScore: 0.7, hueVariance: 750, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.20, saturationAvg: 60, lightnessAvg: 55, warmthScore: 0.7, hueVariance: 800, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.25, saturationAvg: 55, lightnessAvg: 52, warmthScore: 0.6, hueVariance: 700, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.18, saturationAvg: 62, lightnessAvg: 56, warmthScore: 0.8, hueVariance: 890, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.21, saturationAvg: 57, lightnessAvg: 53, warmthScore: 0.7, hueVariance: 740, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.19, saturationAvg: 61, lightnessAvg: 55, warmthScore: 0.7, hueVariance: 810, formalityRange: 1, dominantTraits: ["elegant","bold"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.24, saturationAvg: 56, lightnessAvg: 52, warmthScore: 0.6, hueVariance: 720, formalityRange: 1, dominantTraits: ["elegant","romantic"], label: "Ethnic Festive" },
  { formality: 4.0, neutralRatio: 0.16, saturationAvg: 63, lightnessAvg: 57, warmthScore: 0.8, hueVariance: 910, formalityRange: 1, dominantTraits: ["bold","elegant"], label: "Ethnic Festive" },
  { formality: 4.5, neutralRatio: 0.23, saturationAvg: 57, lightnessAvg: 53, warmthScore: 0.7, hueVariance: 750, formalityRange: 1, dominantTraits: ["elegant","classic"], label: "Ethnic Festive" },

  // ══════════════════════════════════════════════════════════════════════════
  // TRAVEL (20 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 1.5, neutralRatio: 0.35, saturationAvg: 38, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 400, formalityRange: 1, dominantTraits: ["casual","minimalist"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.30, saturationAvg: 40, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 550, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.38, saturationAvg: 36, lightnessAvg: 53, warmthScore: 0.4, hueVariance: 430, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.33, saturationAvg: 39, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 520, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.42, saturationAvg: 34, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 380, formalityRange: 1, dominantTraits: ["casual","minimalist"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.32, saturationAvg: 40, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 540, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.39, saturationAvg: 36, lightnessAvg: 53, warmthScore: 0.4, hueVariance: 420, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.34, saturationAvg: 38, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 510, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.41, saturationAvg: 35, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 390, formalityRange: 1, dominantTraits: ["casual","minimalist"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.31, saturationAvg: 40, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 530, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.37, saturationAvg: 37, lightnessAvg: 54, warmthScore: 0.4, hueVariance: 440, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.33, saturationAvg: 39, lightnessAvg: 55, warmthScore: 0.5, hueVariance: 520, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.40, saturationAvg: 35, lightnessAvg: 52, warmthScore: 0.4, hueVariance: 400, formalityRange: 1, dominantTraits: ["casual","minimalist"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.30, saturationAvg: 40, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 545, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.38, saturationAvg: 36, lightnessAvg: 53, warmthScore: 0.4, hueVariance: 425, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.35, saturationAvg: 38, lightnessAvg: 54, warmthScore: 0.5, hueVariance: 500, formalityRange: 1, dominantTraits: ["casual","classic"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.42, saturationAvg: 34, lightnessAvg: 51, warmthScore: 0.4, hueVariance: 380, formalityRange: 1, dominantTraits: ["casual","minimalist"], label: "Travel" },
  { formality: 1.5, neutralRatio: 0.32, saturationAvg: 39, lightnessAvg: 56, warmthScore: 0.5, hueVariance: 535, formalityRange: 1, dominantTraits: ["casual","sporty"], label: "Travel" },
  { formality: 2.0, neutralRatio: 0.39, saturationAvg: 36, lightnessAvg: 53, warmthScore: 0.4, hueVariance: 415, formalityRange: 1, dominantTraits: ["classic","casual"], label: "Travel" },

  // ══════════════════════════════════════════════════════════════════════════
  // NIGHT OUT (20 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 2.5, neutralRatio: 0.25, saturationAvg: 62, lightnessAvg: 42, warmthScore: 0.4, hueVariance: 1100, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.30, saturationAvg: 58, lightnessAvg: 40, warmthScore: 0.3, hueVariance: 1000, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.20, saturationAvg: 65, lightnessAvg: 43, warmthScore: 0.5, hueVariance: 1200, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.28, saturationAvg: 60, lightnessAvg: 41, warmthScore: 0.4, hueVariance: 1050, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.22, saturationAvg: 63, lightnessAvg: 42, warmthScore: 0.4, hueVariance: 1150, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.32, saturationAvg: 57, lightnessAvg: 40, warmthScore: 0.3, hueVariance: 980, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.18, saturationAvg: 66, lightnessAvg: 44, warmthScore: 0.5, hueVariance: 1250, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.26, saturationAvg: 60, lightnessAvg: 41, warmthScore: 0.4, hueVariance: 1060, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.24, saturationAvg: 62, lightnessAvg: 42, warmthScore: 0.4, hueVariance: 1120, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.30, saturationAvg: 58, lightnessAvg: 40, warmthScore: 0.3, hueVariance: 1000, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.20, saturationAvg: 64, lightnessAvg: 43, warmthScore: 0.5, hueVariance: 1180, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.28, saturationAvg: 59, lightnessAvg: 41, warmthScore: 0.4, hueVariance: 1040, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.22, saturationAvg: 63, lightnessAvg: 42, warmthScore: 0.4, hueVariance: 1140, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.31, saturationAvg: 57, lightnessAvg: 40, warmthScore: 0.3, hueVariance: 990, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.19, saturationAvg: 65, lightnessAvg: 43, warmthScore: 0.5, hueVariance: 1220, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.27, saturationAvg: 60, lightnessAvg: 41, warmthScore: 0.4, hueVariance: 1050, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.23, saturationAvg: 63, lightnessAvg: 42, warmthScore: 0.4, hueVariance: 1130, formalityRange: 1, dominantTraits: ["bold","edgy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.29, saturationAvg: 58, lightnessAvg: 40, warmthScore: 0.3, hueVariance: 1010, formalityRange: 1, dominantTraits: ["edgy","trendy"], label: "Night Out" },
  { formality: 2.5, neutralRatio: 0.21, saturationAvg: 64, lightnessAvg: 43, warmthScore: 0.5, hueVariance: 1190, formalityRange: 1, dominantTraits: ["bold","trendy"], label: "Night Out" },
  { formality: 3.0, neutralRatio: 0.30, saturationAvg: 59, lightnessAvg: 41, warmthScore: 0.4, hueVariance: 1030, formalityRange: 1, dominantTraits: ["edgy","bold"], label: "Night Out" },

  // ══════════════════════════════════════════════════════════════════════════
  // BEACH (15 samples)
  // ══════════════════════════════════════════════════════════════════════════
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 50, lightnessAvg: 65, warmthScore: 0.7, hueVariance: 700, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.15, saturationAvg: 55, lightnessAvg: 68, warmthScore: 0.8, hueVariance: 800, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.25, saturationAvg: 48, lightnessAvg: 63, warmthScore: 0.6, hueVariance: 600, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.18, saturationAvg: 52, lightnessAvg: 66, warmthScore: 0.7, hueVariance: 750, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.22, saturationAvg: 50, lightnessAvg: 64, warmthScore: 0.7, hueVariance: 700, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.16, saturationAvg: 54, lightnessAvg: 67, warmthScore: 0.8, hueVariance: 780, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.24, saturationAvg: 48, lightnessAvg: 63, warmthScore: 0.6, hueVariance: 620, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.19, saturationAvg: 52, lightnessAvg: 66, warmthScore: 0.7, hueVariance: 740, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.21, saturationAvg: 50, lightnessAvg: 65, warmthScore: 0.7, hueVariance: 710, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.17, saturationAvg: 53, lightnessAvg: 67, warmthScore: 0.8, hueVariance: 770, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.23, saturationAvg: 49, lightnessAvg: 64, warmthScore: 0.6, hueVariance: 650, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.18, saturationAvg: 52, lightnessAvg: 66, warmthScore: 0.7, hueVariance: 730, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.20, saturationAvg: 50, lightnessAvg: 65, warmthScore: 0.7, hueVariance: 700, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.15, saturationAvg: 55, lightnessAvg: 68, warmthScore: 0.8, hueVariance: 800, formalityRange: 0, dominantTraits: ["casual","sporty"], label: "Beach" },
  { formality: 1.0, neutralRatio: 0.22, saturationAvg: 49, lightnessAvg: 64, warmthScore: 0.7, hueVariance: 680, formalityRange: 0, dominantTraits: ["casual","bohemian"], label: "Beach" },
];
